# 设置 worflow 的名称，会在 github 的 Action 界面展示
name: ci-test

# 定义可以触发此工作流的事件
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    # 指定该 job 的名称
    name: Test
    # 指定的 runner
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
        # Label used to access the service container
        postgres:
          # Docker Hub image
          image: postgres:12
          # Provide the user password and DB_name(用于指定连接数据库的名称) for postgres
          env:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: simple_bank
          # Set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    
    steps:

    - name: Set up Go 1.19.2
      uses: actions/setup-go@v4
      with:
        go-version: '1.19.2'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    
    - name: Install golang-migrate CLI
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.12.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate.linux-amd64 /usr/bin/
        which migrate

    - name: Run migrations
      # 进行数据库迁移保证数据库的状态
      run: make migrateup

    - name: Test
      # 执行 Makefile 中定义好的命令， make test 实现 go test -v -cover ./... 的效果
      run: make test
